[package]
name = "spaceflight-cli"
version = "0.1.0"
edition = "2021"
authors = [ "8-sided-oregon" ]
description = "Command line Launch Library 2 wrapper."

[dependencies]
clap = "4.1.4"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { version = "1", features = ["full"] }
